import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-input-button-unit',
  standalone: true,
  imports: [],
  template: `
    <input class="todo-input"
        #inputElementRef
        [value]="title"
        placeholder="Write a task"
        (keyup.enter)="submitValue(getInputValue($event))">  
    <div>
      <button class="btn"
        (click) = "submitValue(inputElementRef.value)" >
        Save
      </button>
    </div>
  `,
  styleUrl: './input-button-unit.component.scss'
})

export class InputButtonUnitComponent {
  @Output() submit:EventEmitter<string> = new EventEmitter<string>();

  title = ''
    
  submitValue(newTitle: string): void {
    console.log('avantsubmit');
    
    this.submit.emit(newTitle);
    console.log(newTitle);
    
  }  

  getInputValue(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }


  // constructor() { 
  //   // setTimeout (() => {
  //   this.submitValue('');
  //   console.log(this.works);
  //   // }, 3000)
  // }

  // generateTitle(): string {
  //   return 'This title was generated by a method.';
  // }
}

